# Generated by Django 5.0.6 on 2024-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('', '--Select Gender--'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('', '--Select Blood Group--'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('mobile_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
